# Calidad de Aguas
## Alcance y objetivos

Esta sección se enfoca en el análisis de los datos disponibles de calidad del agua obtenidos en estaciones de monitoreo de agua superficial y subterránea aguas arriba y aguas abajo de la obturación. El objetivo de esta etapa consiste en evaluar el desempeño en términos de su impacto en los parámetros de calidad de agua aguas arriba y aguas abajo de la obturación, y poder correlacionar los desvíos respecto de la línea base con eventos climáticos, operacionales o de mantenimiento de la obturación.

Para la evaluación de la calidad del agua, el presente documento incorpora el concepto de carga de soluto, expresada en Kg/h en este documento, la cual resulta de la multiplicación del caudal por la concentración del soluto, con la muestra de agua tomada el mismo día en que se midió el caudal. En comparación con la evaluación de solo las concentraciones, la carga de soluto permite evaluar con mayor claridad la contribución de determinado soluto por parte de cada curso de agua.

\

## Estaciones de monitoreo seleccionadas

- **LA-1A**: se ubica sobre el tramo superior del arroyo Turbio, inmediatamente aguas arriba del portal del túnel y del área de tratamiento de agua ácida y control de pH que estuvo en funcionamiento durante el periodo de túnel abierto (2011-2013). El caudal del arroyo Turbio en este tramo disminuyó durante la excavación debido al “efecto dren” del túnel, el cual drenó una parte importante del caudal superficial y subálveo del arroyo, así como el agua de almacenamiento del acuífero de fracturas del macizo rocoso. Al ser el agua de signatura hidroquímica fuertemente sulfatada-cálcica, se observó precipitación de yeso en los bancos del arroyo durante el periodo de caudal bajo (2011-2013). El agua del arroyo Turbio y del acuífero del macizo rocoso es naturalmente ácida (pH ~3) y carga alta de sulfato y metales tales como aluminio, hierro, manganeso, cobre, níquel y zinc, entre otros.
- **MAR-1**: está ubicada en el portal del túnel y capta el agua drenada por el túnel, previamente al sistema de tratamiento de control del pH. El agua monitoreada en esta estación proviene del sistema del arroyo Turbio y del macizo rocoso, posiblemente con modificaciones químicas menores debidas al cemento utilizado en el revestimiento interno del túnel.
- **TUN-1**: se localiza inmediatamente a la salida del sistema de tratamiento de control del pH y recibe el drenaje del túnel luego de ser tratado con cal apagada (Ca (OH)2). Estuvo activa hasta la suspensión del tratamiento del agua con cal apagada, el 5 de abril de 2019.
- **LA-8**: se ubica sobre el cauce del río Turbio, inmediatamente antes de la desembocadura del río de Las Taguas. En esta estación se monitorea actualmente el agua proveniente de los arroyos Canito y Turbio, así como el agua residual proveniente del túnel luego de su cierre. El registro de caudal y química del agua muestra variaciones marcadas, directamente relacionadas a las obras de desvío y conducción que funcionaron en la cuenca de Canito entre 2014 y fines de 2020.
- **SW-9**: es la primera estación de monitoreo sobre el río de Las Taguas que recibe la descarga desde las cuencas de Canito y Turbio (ya monitoreada en LA-8).
- **LA-16**: se ubica sobre el río Las Taguas, aguas abajo de la confluencia con el arroyo de Los Amarillos. Es el punto de cumplimiento legal del proyecto Lama.

## Sistema de conducción de agua en Lama

Algunos cursos de agua en los sistemas Canito y Turbio fueron afectados por desvíos relacionados a obras de manejo de agua, lo cual se vio reflejado en su registro de monitoreo. Las modificaciones de los cursos de agua en las cuencas de Canito y Turbio comenzaron en enero de 2014 y estuvieron vigentes hasta noviembre de 2020. Un resumen de la configuración de los sistemas de conducción de agua en las cuencas de Canito y Turbio, antes y después de noviembre/diciembre de 2020, puede encontrarse en el informe del IDIH (2024), el cual sintetiza los resultados del monitoreo de calidad de agua en el proyecto Lama desde enero de 2012 hasta diciembre de 2023. Los siguientes son extractos del informe del IDIH (2024) que resumen las configuraciones de los sistemas de conducción de agua.

El siguiente texto son extractos del informe de monitoreo IDIH XXX, para las configuraciones previas y posteriores a noviembre de 2020. El esquema citado como “Figura 1” y “Figura 2” por IDIH (2024) se muestra aquí como XXXX.



_Las aguas del arroyo Canito Sur se monitorean en la estación CA-1 que es un punto crítico de control establecido para monitorear la calidad de las aguas en el ingreso al área de la mina LAMA, y que está ubicada en la parte alta de la cuenca aguas arriba de la estación LA-3. En el arroyo Canito Norte se desvía parte de las aguas por el Canal de Descarga 2 (CD2) y continúa como Tubería de Desvío 1 (TD1), hacia el arroyo Turbio. El agua superficial del arroyo Canito se monitorea en la estación LA-3, y continua por el Canal de Desvío 4 (CD4), acorde al proyecto de Obras de Desvío presentado y aprobado por las autoridades competentes. Este canal se encuentra con las aguas subterráneas del Dique de Colas (estación de monitoreo UD) y ambos desembocan en el antiguo cauce del Río Turbio, donde son monitoreados en el punto LA-8, antes de la confluencia con el Río Las Taguas. Ver Figura 1._

_La cuenca del río Turbio se monitorea en la parte alta en la estación LA-1a, las aguas superficiales son entubadas en la Tubería de Desvío 2 (TD2) que recibe en su recorrido las aguas tratadas del túnel, las aguas del sub dren de la planta de proceso y parte de las aguas del arroyo Canito transportadas por el TD1, y a partir de allí comienza la Tubería de Desvío 3 (TD3) cuyas aguas se monitorean en la estación LA-8a, antes de la confluencia con el río de Las Taguas. Ver Figura 1._

_A partir de diciembre de 2020, el sistema de manejo de aguas de la cuenca del río Turbio se modificó nuevamente, como muestra la Figura 2, donde las aguas del arroyo Turbio y Canito se unen nuevamente y las aguas superficiales de la cuenca del río Turbio se monitorean en la estación LA-8, y se deja de monitorear la estación LA-8a._

Figura 4‑1: Figura 1 y Figura 2 en el informe del IDIH (2024)


## Fechas relevantes

Las siguientes viñetas son una breve reseña de las fechas aproximadas de eventos que tienen relevancia en el análisis de monitoreo de calidad de agua, relacionado al túnel Marcelo y a su obturación.

- Alumbramiento de agua en la excavación del túnel: no se encontró un documento que indique una fecha exacta, aunque se estima que desde principios de 2011.\
- Comienzo del tratamiento de clarificación en el interior del túnel: aproximadamente marzo de 2012. Constituyó una planta de clarificación (AGUASIN) y se encontraba en el interior del túnel, no se incluía adición de cal.\
- Comienzo del tratamiento con cal en el portal del túnel: julio de 2012.\
- Suspensión de la excavación del túnel: diciembre de 2013.\
- Máximo caudal registrado a túnel abierto (250 L/s): enero de 2017.\
- Inicio de la construcción del tapón: 17 de agosto de 2017.\
- Cierre de válvulas del tapón: 12 de enero de 2018.\
- Suspensión del agregado de cal: abril de 2019.\
- Inicio de obras de desvío y conducción entre las cuencas de Canito y Turbio: enero de 2014 (IDIH, 2024)
- Reconfiguración del sistema de conducción de agua entre las cuencas de Canito y Turbio: noviembre/diciembre de 2020.
## Caudales

### Sector del túnel

Las series temporales de las estaciones de este sector se muestran en la Figura 4‑2.

El caudal en LA-1A es altamente variable durante el día debido a que este arroyo tiene una alta dependencia de los deshielos en su tramo superior, por lo que los puntos en el gráfico representan un promedio diario. El caudal en este punto decreció por el efecto drenante del túnel y en general se mantuvo relativamente bajo, con registros promedio entre 5 y 20 L/s, a excepción de un evento con caudales promedio de hasta 170 L/s entre noviembre de 2015 y enero de 2016, debido a precipitaciones intensas en invierno de 2015 registradas en la estación de Barreal. **Luego del cierre de las válvulas del tapón del túnel en enero de 2018, el caudal se incrementó fuertemente[[1]](#_ftn1) por recuperación del caudal drenado y luego un decrecimiento más suave hasta caudales promedio en el orden de 30 L/s.** El caudal en MAR-1 evolucionó en picos que se daban cuando la excavación del túnel encontraba una zona de mayor conductividad hidráulica (e.g. zona de falla o de mayor fracturamiento) y valles que se daban cuando dicho caudal se drenaba y disminuía el nivel piezométrico. El caudal en TUR-1 tuvo casi la misma serie que el caudal en MAR-1.

Figura 4‑2: series temporales de caudales en las estaciones del sector del túnel. El campo verde indica túnel abierto y el campo celeste túnel cerrado.

### Sector de la desembocadura al río de Las Taguas

La serie temporal de la estación LA-8 se muestra en la Figura 4‑3.

El caudal estuvo en baja desde los primeros registros y se mantuvo en valores relativamente bajos (~70-100 L/s) entre 2014 y fines de 2020, cuando LA-8 no recibía agua superficial de la cuenca del río Turbio. **El caudal presenta una tendencia decreciente desde el cierre de las válvulas y se encuentra en tendencia creciente desde la reconexión de las cuencas de Canito y Turbio, con la mayor parte de los valores en el rango 100-175 L/s, similares a los medidos al principio del registro.** Se registraron los eventos de alto caudal relacionados a las precipitaciones nivales durante los inviernos de 2015 y 2017. **Los caudales en el portal del túnel, registrados actualmente en MAR-1, disminuyeron súbitamente luego del cierre de válvulas del tapón, con un valor máximo de 13 L/s inmediatamente luego del cierre y una estabilización en torno a 5 L/s**.

Figura 4‑3: serie temporal de caudal en el sector de la desembocadura al río de Las Taguas. El campo verde indica túnel abierto y el campo celeste túnel cerrado.

### Sector del río de Las Taguas

Las series temporales de las estaciones de este sector se muestran en la Figura 4‑4.

Los caudales en SW-9 y LA-16 presentan series temporales muy similares, tanto en valores de caudal como en evolución. Se registraron los picos de alto caudal (en el orden de 3000-3500 L/s) relacionados a los inviernos de 2015 y 2017, y uno intermedio entre octubre y diciembre de 2016. **Los caudales se mantuvieron relativamente altos (~1000-1500 L/s) luego del cierre de las válvulas en enero de 2018 y mostraron una tendencia decreciente desde aproximadamente septiembre de 2019, hasta un rango relativamente amplio de 350-900 L/s, similar al registrado previamente a la apertura del túnel, aunque sin una relación directa con dicho cierre.**

Figura 4‑4: series temporales de caudales en las estaciones del sector del río de Las Taguas. El campo verde indica túnel abierto y el campo celeste túnel cerrado.

## Sulfato

### Sector del túnel

Las series temporales para concentración de sulfato de las estaciones de este sector se muestran en la Figura 4‑5, mientras que las correspondientes a la carga de sulfato se muestran en la Figura 4‑6.

La concentración de sulfato en LA-1A decreció desde aproximadamente marzo de 2013, posiblemente debido a la mayor influencia de los deshielos hacia este curso durante caudal bajo (túnel abierto), aunque con menor frecuencia de medición. En general, las concentraciones bajas coinciden con caudales altos. **La concentración en este punto aumentó a tasa relativamente alta desde el cierre de las válvulas en enero de 2018 y luego la tendencia se hizo más suave, con valores fluctuantes mayormente entre 2400 y 4000 mg/L.**

Las concentraciones de sulfato en TUN-1 fueron más bajas que en MAR-1 debido a la siguiente reacción de neutralización simplificada durante el tratamiento del agua naturalmente sulfatada con cal apagada (el sulfato precipitando en la especie yeso):

$H_2SO_4 (ac) + Ca(OH)_2 (ac) → CaSO_4 (s) + 2H_2O(l)$

**Luego del cierre de las válvulas del tapón del túnel, la tendencia fue similar a la de LA-1A, estabilizándose en valores de ~1800-2800 mg/L.**

Al observar las cargas de sulfato registradas en las tres estaciones, las diferencias son más claras marcadas. En LA-1A, la carga de sulfato fue disminuyendo durante la etapa de túnel abierto debido a una disminución del caudal por efecto drenante del túnel. **Luego del cierre de las válvulas, hubo un aumento marcado por recuperación del caudal y posiblemente por redisolución del yeso que había precipitado en los bancos durante caudal bajo, para luego mostrar una tendencia decreciente hasta valores de ~380-550 kg/h. En MAR-1, actualmente la única estación donde se monitorea la calidad del agua en la zona del portal del túnel, la carga de sulfato se estabilizó en valores mínimos entre 20 y 54 kg/h**.

Figura 4‑5: series temporales de concentración de sulfato en el sector del túnel. Se indica el periodo de agregado de cal apagada en el portal del túnel.

Figura 4‑6: series temporales de carga de sulfato en el sector del túnel. Se indica el periodo de agregado de cal apagada en el portal del túnel.

### Sector de la desembocadura al río de Las Taguas

La serie temporal para concentración de sulfato en LA-8 se muestra en la Figura 4‑7, mientras que la correspondiente a la carga de sulfato se muestra en la Figura 4‑8.

El periodo en que las cuencas de Canito y Turbio estuvieron desconectadas está marcado por una fuerte baja en la concentración de sulfato (fuerte influencia del arroyo Canito, más diluido en sulfato). La influencia del cierre de las válvulas del tapón del túnel no se nota en esta serie temporal, como sí ocurre desde que ambas cuencas volvieron a conectarse y la concentración de sulfato aumentó nuevamente a valores más comparables al periodo previo a las obras de desvío.

La serie temporal de carga de sulfato muestra una tendencia decreciente previo a los desvíos, una estabilización a valores en torno a ~300 kg/h durante el periodo de ambas cuencas desconectadas y una tendencia creciente con el aporte del agua del arroyo Turbio desde la reconexión de ambas cuencas, hasta valores generalmente entre 700 y 1300 kg/h.

Figura 4‑7: serie temporal de concentración de sulfato en LA-8, previo a la desembocadura en el río de Las Taguas.

Figura 4‑8: serie temporal de la carga de sulfato en LA-8, previo a la desembocadura en el río de Las Taguas.

### Sector del río de Las Taguas

Las series temporales para concentración de sulfato de las estaciones de este sector se muestran en la Figura 4‑9, mientras que las correspondientes a la carga de sulfato se muestran en la Figura 4‑10.

Las estaciones SW-9 y LA-16 muestran series temporales de sulfato similares, con una mayor frecuencia de medición en LA-16, ya que es el punto de cumplimiento. Las concentraciones de sulfato fueron muy variables durante el periodo de túnel abierto, con periodos de concentración baja coincidentes con eventos de caudal alto. Luego del cierre de las válvulas del tapón del túnel, disminuyó la frecuencia de medición aunque las concentraciones continuaron con alta variabilidad relacionadas en general a variabilidad de caudales. No se observa claramente una tendencia creciente o decreciente luego del cierre del túnel.

En cuanto a la carga de solutos, las series temporales de ambas estaciones muestran un aumento durante el periodo de túnel abierto, con una tendencia decreciente luego del cierre de las válvulas y levemente más marcada luego del cese de agregado de cal apagada. Desde aproximadamente enero de 2021, los valores de carga de sulfato son variables aunque en torno a los previos a la apertura del túnel.

Figura 4‑9: serie temporal de concentración de sulfato en el sector del río de Las Taguas.

Figura 4‑10: serie temporal de la carga de sulfato en el sector del río de Las Taguas.

## pH

### Sector del túnel

Las series temporales para el monitoreo de pH de las estaciones de este sector se muestran en la Figura 4‑11.

Durante la etapa de túnel abierto, el pH registrado en la estación TUN-1 fue muy variable de acuerdo con el ritmo de adición de cal apagada, aunque en general por encima de un valor de 5. En el caso del arroyo Turbio (**LA-1A**), el valor más frecuente estuvo entre 3 y 3,5, **estabilizándose a un valor más cercano a 3 luego del cierre de las válvulas del tapón, posiblemente debido a un aumento del caudal y menor impacto de los deshielos en este parámetro**. En general, el pH en el portal del túnel (MAR-1) estuvo y se mantiene ligeramente por encima del pH del arroyo Turbio, posiblemente debido a una cierta neutralización por el cemento utilizado en el revestimiento del túnel o un mayor impacto de dilución debida a deshielos.

Figura 4‑11: series temporales de pH en el sector del túnel. Se indica el periodo de agregado de cal apagada en el portal del túnel.

### Sector de la desembocadura al río de Las Taguas

La serie temporal de pH en la estación de monitoreo LA-8 se muestra en la Figura 4‑12.

El fue variable, pero en valores relativamente altos (en torno a ~4) durante parte del periodo de túnel abierto y todo el periodo de ambas cuencas desconectadas. **Se observa una disminución muy leve del pH luego del cierre del túnel y en especial de abril de 2019 (cese de agregado de cal en el portal del túnel) y una disminución marcada luego de la reconexión de ambas cuencas, hacia valores en torno a 3,4, más cercanos a los valores del arroyo Turbio**.

Figura 4‑12: serie temporal de pH en el sector de la desembocadura al río de Las Taguas. Se indica el periodo en que ambas cuencas estuvieron desconectadas por obras de desvío.

### Sector del río de Las Taguas

La serie temporal de pH en las estaciones que representan el sector del río de Las Taguas para el proyecto Lama se muestran en la Figura 4‑13.

El pH en SW-9 y LA-16 se presentó ampliamente variable a lo largo de todo el registro (mayormente ~4,5-8,5), con una mayor frecuencia de medición durante el periodo de túnel abierto. **La tendencia de los valores de pH fue levemente decreciente luego del cierre de las válvulas y luego del cese de adición de cal apagada, aunque aún dentro del rango de valores registrados previamente a la excavación del túnel y aún durante el periodo de túnel abierto**.

Figura 4‑13: serie temporal de pH en el sector del río de Las Taguas. Se indica el periodo de agregado de cal apagada en el portal del túnel.

## Aluminio

### Sector del túnel

Las series temporales para concentración de aluminio de las estaciones de este sector se muestran en la Figura 4‑15, mientras que las correspondientes a la carga de aluminio se muestran en la Figura 4‑14.

La serie temporal de concentración de LA-1A muestra concentraciones muy variables (~100-450 mg/L) previamente a la apertura del túnel, con un rango similar aunque con menor frecuencia de medición durante el periodo de túnel abierto, posiblemente debido al congelamiento de su cauce reducido por efecto drenante del túnel. **Luego del cierre de las válvulas, se observa una tendencia creciente fuerte, la cual permanece en aumento pero con pendiente más suave desde aproximadamente abril de 2019**. Las tendencias de la concentración de aluminio en MAR-1 y TUN-1 muestran una mejor definición de dicha variabilidad (mayor frecuencia de medición). **La tendencia en MAR-1 es también creciente luego del cierre del túnel aunque con contenidos menores, sugiriendo que la mayor fuente de aluminio en el sector es el arroyo Turbio más que el macizo rocoso (lo mismo para el sulfato)**.

**Las series temporales de la carga de aluminio muestran una tendencia estable luego del cierre del túnel tanto para LA-1A, a pesar de que su caudal se mostró con tendencia decreciente en este periodo, como para MAR-1, con caudales residuales bajos (hoy en el orden de 5 L/s)**.

Figura 4‑14: series temporales de la concentración de aluminio en las estaciones de monitoreo del sector del túnel. Se indica el periodo de adición de cal en el portal del túnel.

Figura 4‑15: series temporales de la carga de aluminio en las estaciones de monitoreo del sector del túnel. Se indica el periodo de adición de cal en el portal del túnel.

### Sector de la desembocadura al río de Las Taguas

La serie temporal para concentración de aluminio en LA-8 se muestra en la Figura 4‑16, mientras que la correspondiente a la carga de aluminio se muestra en la Figura 4‑17.

De forma similar a la del sulfato (Figura 4‑7 y Figura 4‑8), las series temporales de concentración y carga de aluminio decrecen, se estabilizan en valores bajos en el periodo en que LA-8 registraba calidad de agua principalmente de la cuenca de Canito, **y muestran una tendencia de aumento luego de la reconexión entre ambas cuencas. La influencia del cierre del túnel y del cese de adición de cal es de mucha menor relevancia para este parámetro.**

Figura 4‑16: serie temporal de la concentración de aluminio en el sector de la desembocadura al río de Las Taguas (LA-8). Se indica el periodo en que las cuencas de Canito y Turbio estuvieron desconectadas.

Figura 4‑17: serie temporal de la carga de aluminio en el sector de la desembocadura al río de Las Taguas (LA-8). Se indica el periodo en que las cuencas de Canito y Turbio estuvieron desconectadas.

### Sector del río de Las Taguas

Las series temporales para concentración de aluminio de las estaciones de este sector se muestran en la Figura 4‑18, mientras que las correspondientes a la carga de aluminio se muestran en la Figura 4‑19.

Las series temporales muestran una evolución similar en las estaciones SW-9 y LA-16, tanto en concentración como en carga de soluto. La concentración de aluminio es ampliamente variable y presenta una tendencia generalmente ascendente a lo largo del registro en ambas estaciones, con valores relativamente altos durante la etapa de túnel abierto. **La tendencia se observa ascendente, desde valores bajos, luego del cierre de las válvulas, con concentraciones aún dentro del rango de la etapa de túnel abierto aunque con amplia variabilidad**.

Los picos en carga de aluminio coinciden aproximadamente con picos en el caudal registrado en la boca del túnel cuando se encontraba abierto. **La tendencia de la carga de aluminio se estabiliza luego del cierre de las válvulas, aunque con mediciones puntuales por encima de la tendencia general**.

Figura 4‑18: serie temporal de la concentración de aluminio en el sector del río de Las Taguas. Se indica el periodo de agregado de cal apagada en el portal del túnel.

Figura 4‑19: serie temporal de la carga de aluminio en el sector del río de Las Taguas. Se indica el periodo de agregado de cal apagada en el portal del túnel.

## Hierro

### Sector del túnel

Las series temporales para concentración de hierro de las estaciones de este sector se muestran en la Figura 4‑20, mientras que las correspondientes a la carga de hierro se muestran en la Figura 4‑21.

La concentración de hierro fue variable en LA-1A (~200-500 mg/L), con mediciones más espaciadas aproximadamente entre febrero de 2014 y diciembre de 2017. **A partir del cierre de las válvulas del tapón del túnel, se observa una tendencia creciente fuerte aproximadamente hasta septiembre de 2018 y luego una tendencia más suave aunque aún creciente**. **Las concentraciones de hierro registradas en MAR-1 y TUN-1 fueron variables aunque relativamente altas en la etapa de túnel abierto, disminuyeron con el cierre del túnel (~30-60 mg/L) y luego mostraron un aumento al principio empinado que evolucionó a una tendencia levemente ascendente en torno a concentraciones entre ~200 y 380 mg/L**.

Figura 4‑20: serie temporal de concentración de hierro en el sector de influencia del túnel.

Figura 4‑21: serie temporal de carga de hierro en el sector de influencia del túnel.

### Sector de la desembocadura al río de Las Taguas

La serie temporal para concentración de hierro en LA-8 se muestra en la Figura 4‑22, mientras que la correspondiente a la carga de hierro se muestra en la Figura 4‑23.

La concentración de hierro se observa en un rango amplio (~20-100 mg/L) pero de tendencia estable previamente a la desconexión de las cuencas de Canito y Turbio y desciende a valores muy bajos (en torno a 5mg/L) en el periodo en que ambas cuencas estuvieron desconectadas. **Luego de la reconexión entre ambas cuencas, los valores de concentración se recuperaron aunque la tendencia que se mantiene hasta la actualidad es ascendente**. **La serie temporal de carga de hierro muestra también una tendencia ascendente luego de la reconexión entre ambas cuencas**.

Figura 4‑22: serie temporal de la concentración de hierro en el sector de la desembocadura al río de Las Taguas (LA-8). Se indica el periodo en que las cuencas de Canito y Turbio estuvieron desconectadas.

Figura 4‑23: serie temporal de la carga de hierro en el sector de la desembocadura al río de Las Taguas (LA-8). Se indica el periodo en que las cuencas de Canito y Turbio estuvieron desconectadas.

### Sector del río de Las Taguas

Las series temporales para concentración de hierro de las estaciones del sector del río de Las Taguas se muestran en la Figura 4‑24, mientras que las correspondientes a la carga de aluminio se muestran en la Figura 4‑25.

Las concentraciones de hierro medidas en ambas estaciones durante el periodo de túnel abierto se presentan en un rango amplio, aunque con una mayor frecuencia de valores relativamente altos en comparación con la etapa previa al túnel. Luego del cierre de las válvulas, se observa una disminución general de las concentraciones de hierro y la tendencia parece ser estable, aunque el rango de valores medidos aún es amplio.

Figura 4‑24: serie temporal de la concentración de hierro en el sector del río de Las Taguas. Se indica el periodo de agregado de cal apagada en el portal del túnel.

Figura 4‑25: serie temporal de la carga de hierro en el sector del río de Las Taguas. Se indica el periodo de agregado de cal apagada en el portal del túnel.

## Comentarios finales

**Caudales**

En el sector del túnel, la excavación del túnel Marcelo por debajo del nivel de saturación del macizo rocoso tuvo como consecuencias:

- El drenado del acuífero de fracturas del macizo rocoso, provocando la disminución del nivel piezométrico y el secado temporal de algunos puntos de afloramientos de agua en la superficie del terreno por encima de la traza del túnel.

- El drenado del subálveo del arroyo Turbio, causando una disminución del caudal superficial de este curso de agua.

El agua del drenado del macizo rocoso y del subálveo del arroyo Turbio se condujo a través del túnel y se monitoreó en la estación MAR-1, mientras que el agua superficial remanente del tramo inferior del arroyo Turbio se monitoreó en la estación LA-1A.

Los aumentos marcados en el caudal del arroyo Turbio durante la etapa de túnel abierto fueron eventuales y posteriores a periodos caracterizados por precipitaciones de nieve intensas, especialmente los ocurridos en los años 2015 y 2017, que afectaron toda la zona y sus efectos fueron registrados en las estaciones de monitoreo aguas abajo. Los eventos de caudal alto del agua del túnel monitoreada en MAR-1estuvieron relacionados a la intercepción de zonas de alto fracturamiento durante la excavación del túnel, los cuales se estabilizaban a medida que descendía el nivel piezométrico, y sucediendo inviernos de nevadas intensas (e.g. verano de 2018).

Luego del cierre de las válvulas del tapón del túnel en enero de 2018, el caudal en el arroyo Turbio aumentó rápidamente a valores en torno a 75 L/s y luego fue decreciendo hasta valores actuales de ~30 L/s. En el portal del túnel, se registró un caudal máximo de unos 13 L/s inmediatamente luego del cierre y se estabilizó rápidamente en el orden de 5 L/s.

El caudal residual en MAR-1 se mantuvo en torno a 5-6 L/s desde mayo de 2018 y no registró variaciones relevantes, a pesar de las variaciones anuales (en el orden de 7 a 10 m) en la altura piezométrica correspondiente a la solera del túnel obturado en la cual se registraron máximos en marzo-abril de cada año (XXXX). Tampoco se manifestaron cambios relacionados con las variaciones de caudal del arroyo Turbio.

![Gráfico, Gráfico de líneas
Descripción generada automáticamente](file:////Users/averri/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_image001.jpg)[[CD1]](#_msocom_1) 

**Se concluye que la obturación del túnel Marcelo es un mecanismo eficiente para la contención del agua que drenaría a túnel abierto, manteniendo caudales residuales (~5 L/s) de aproximadamente un 25% de los permitidos por La Autoridad (20 L/s)[**[1]**](#_ftn1), los cuales no se han visto afectados ni por variaciones en la presión hidrostática aguas arriba del tapón ni por variaciones en el caudal del arroyo Turbio.**

En el sector inmediatamente aguas arriba de la desembocadura del agua superficial de las cuencas de Canito y Turbio en el río de Las Taguas, las variaciones más relevantes de caudal estuvieron relacionadas a las obras de desconexión y conexión de ambas cuencas. Se observaron aumentos más bien eventuales del caudal, relacionadas a años de registros de alta precipitación nival (e.g. 2015 y 2017), que afectaron toda la zona.

En el sector del río de Las Taguas, se observaron los mismos picos de caudal relacionados a años de precipitaciones intensas de nieve y no se notaron variaciones que puedan correlacionarse directamente con las obras de desvío en las cuencas de Canito y Turbio. A partir de la obturación total del túnel Marcelo en enero de 2018, puede notarse una disminución de los caudales en este tramo, aunque esta tendencia es similar a la del arroyo Turbio y parece estar relacionada a una disminución general de las precipitaciones en los últimos 5 años. Incluso el periodo de máximo caudal en el túnel, ~200-250 L/s entre diciembre de 2016 y marzo de 2017, coincidió con el periodo de máximo registro del caudal en el río de Las Taguas, 2200-3200 L/s en LA-16, aunque la contribución del caudal del túnel fue de menos del 10% del caudal del río de Las Taguas y es poco probable que haya causado tales picos.

**Se concluye que las variaciones relevantes y medibles en el caudal del río de Las Taguas, desde su punto de confluencia en LA-8, están relacionadas principalmente a años hidrológicos de distinta característica y no al desarrollo del túnel ni a su posterior obturación.**

**Calidad de agua**

Los informes de monitoreo desde la etapa de línea de base y los distintos estudios hidroquímicos han mostrado que las concentraciones más altas en sulfato, aluminio, hierro y cobre (además de otros metales como zinc, níquel y cobalto) provienen de la cuenca del arroyo Turbio, cuya cabecera escurre por la zona de intensa alteración hidrotermal del yacimiento Pascua-Lama. De esta forma, el arroyo Turbio es un contribuyente importante de los parámetros mencionados al río de Las Taguas.

Se considera que la inclusión de las cargas de solutos (caudal x concentración en fecha coincidente) es una herramienta muy útil para evaluar la contribución de la química de un afluente a un receptor, ya que la observación de las concentraciones por sí solas no permite evaluar la fracción de determinado parámetro que llega a dicho receptor. Por esta razón, la influencia de la obturación del túnel Marcelo fue evaluada por medio de las cargas de soluto. Se evaluó además el pH como un parámetro indicador relacionado a la contribución de agua ácida y el tratamiento de regulación con cal apagada.

En el sector del túnel, el pH ligeramente más alto registrado previo al tratamiento (MAR-1) en comparación con el arroyo Turbio, puede deberse a un consumo menor de acidez por parte del cemento del revestimiento del túnel y/o una mayor influencia de la infiltración de agua de deshielo en el macizo. La carga de sulfato disminuyó con la disminución del caudal en el arroyo Turbio durante el drenado de su subálveo por el túnel, luego se recuperó rápidamente luego del cierre de las válvulas, por recuperación de su caudal y posible redisolución de yeso precipitado durante caudal bajo, y luego mostró una tendencia decreciente. En el portal del túnel, la carga de sulfato se ha mantenido en torno a un valor muy bajo en el orden de 45 kg/h. Las cargas metálicas de aluminio, hierro y cobre presentaron una tendencia decreciente en el periodo de drenaje libre del túnel, con una recuperación y una estabilización luego del cierre de las válvulas. Estas cargas se mantienen en valores mínimos en el portal luego de la obturación del túnel.

**Se concluye que en el sector del túnel, los cambios de pH más relevantes se dieron en el portal por la adición de cal, valores que están tendiendo a estabilizarse luego del cierre del túnel y cese del tratamiento de adición de cal. Las cargas de solutos están mostrando una tendencia a valores previos al drenado por el túnel en el arroyo Turbio y se mantienen en valores muy bajos y estables en el portal.**

En LA-8, estación actual de monitoreo inmediatamente aguas arriba de la confluencia con el río de Las Taguas, el pH aumentó durante el periodo en que el principal contribuyente fue el arroyo Canito. El pH retornó a sus valores previos a las obras de desvío luego de la reconexión de ambas cuencas. Las cargas de sulfato, aluminio, hierro y cobre mostraron una evolución similar, con una disminución y estabilización en valores bajos durante el periodo de desvíos y desconexión entre ambas cuencas y una tendencia ascendente hacia valores previos a los desvíos.

**Se concluye que los cambios en la calidad del agua superficial en este sector están relacionados principalmente a las obras de desvío que aislaron y reconectaron ambas cuencas.**

En el sector del río de Las Taguas, si bien el pH se encuentra actualmente dentro del rango establecido antes de la apertura del túnel, ha decrecido desde el cierre del túnel y la mayor parte de los puntos se ha estabilizado en valores en torno a 5-6. Las cargas de sulfato, aluminio, hierro y cobre mostraron una evolución similar con valores relativamente altos durante el periodo de túnel abierto y una tendencia a estabilizarse en valores más bajos luego del cierre del túnel, cercanos a los previos a la excavación del túnel.

Con los datos disponibles, pueden realizarse estimaciones expeditivas para obtener una primera idea de las contribuciones más importantes del sector del túnel y arroyo Turbio al río de Las Taguas. La fracción aproximada de sulfatos del arroyo Turbio puede estimarse en aproximadamente 20-25%, mientras que la fracción actual desde el portal sería del 2% o inferior. La contribución de aluminio desde el portal del túnel (TUR-1) fue de más del 50% durante el periodo de túnel abierto y adición de cal, disminuyendo al 3-5% luego del cierre. Actualmente, la principal contribución de aluminio al río de Las Taguas proviene del arroyo Turbio (~40-60%). Situaciones similares se observan para hierro y cobre desde el portal del túnel, con contribuciones generalmente superiores al 60% durante el periodo de túnel abierto y adición de cal, y fracciones actuales de ~4-5% desde los caudales residuales (MAR-1). El mayor contribuyente actual de hierro y cobre al río de Las Taguas es el arroyo Turbio (en general más del 70% de la carga metálica).

**Se concluye que, actualmente, las cargas más significativas de sulfato y metales (Al, Fe y Cu, entre otros) provienen actualmente del arroyo Turbio, cuyo caudal ha aumentado luego del cierre del túnel y tiende a valores previos al túnel. Las cargas de sulfato y metales provenientes del portal del túnel son mínimas, con fracciones mínimas (2-5%) y estables.**

  
