## Calidad de Aguas {#sec-QUAL}


El objetivo de este capítulo consiste en evaluar el desempeño del sistema de obturación del teunel, en términos de los parámetros de calidad de agua aguas arriba y aguas abajo de la obturación, y poder correlacionar los desvíos respecto de la línea base con eventos climáticos, operacionales o de mantenimiento de la obturación. En este capítulo se analizan las concentraciones y cargas metálicas de los parámetros más relevantes en términos de calidad de agua, tales como sulfatos, acidez, aluminio, y hierro, en las estaciones de monitoreo ubicadas en el arroyo Turbio, el río de Las Taguas y el portal del túnel.

Las concentraciones, medidas en mg/L o ppm, son particularmente sensibles a las fuertes variaciones estacionales del caudal en los diferentes cursos de agua. Para normalizar este parámetro, se incorpora el concepto de carga de soluto, expresada en Kg/h. La carga de soluto permite evaluar con mayor claridad la contribución de determinado soluto por parte de cada curso de agua y resulta una herramienta muy útil para evaluar la contribución de la química de un afluente a un receptor, ya que la observación de las concentraciones por sí solas no permite evaluar la fracción de determinado parámetro que llega a dicho receptor. Por esta razón, la influencia de la obturación del túnel Marcelo fue evaluada por medio de las cargas de soluto. Se evaluó además el pH como un parámetro indicador relacionado a la contribución de agua ácida y el tratamiento de regulación con cal apagada.

### Sulfatos

La concentración de sulfato en **LA-1A** decreció desde aproximadamente marzo de 2013, posiblemente debido a la mayor influencia de los deshielos hacia este curso durante caudal bajo (túnel abierto), aunque con menor frecuencia de medición. En general, las concentraciones bajas coinciden con caudales altos. La concentración en este punto aumentó a tasa relativamente alta desde el cierre de las válvulas en enero de 2018 y luego la tendencia se hizo más suave, con valores fluctuantes mayormente entre 2400 y 4000 mg/L.

Las concentraciones de sulfato en **TUN-1** fueron más bajas que en **MAR-1** debido a la siguiente reacción de neutralización simplificada durante el tratamiento del agua naturalmente sulfatada con cal apagada (el sulfato precipitando en la especie yeso):

$$H_2SO_4 (ac) + Ca(OH)_2 (ac) → CaSO_4 (s) + 2H_2O(l)$$

Luego del cierre de las válvulas del tapón del túnel, la tendencia fue similar a la de LA-1A, estabilizándose en valores de ~1800-2800 mg/L.

Al observar las cargas de sulfato registradas en las tres estaciones, las diferencias son más claras marcadas. En **LA-1A**, la carga de sulfato fue disminuyendo durante la etapa de túnel abierto debido a una disminución del caudal por efecto drenante del túnel. Luego del cierre de las válvulas, hubo un aumento marcado por recuperación del caudal y posiblemente por redisolución del yeso que había precipitado en los bancos durante caudal bajo, para luego mostrar una tendencia decreciente hasta valores de ~380-550 kg/h. En **MAR-1**, actualmente la única estación donde se monitorea la calidad del agua en la zona del portal del túnel, la carga de sulfato se estabilizó en valores mínimos entre 20 y 54 kg/h.

El periodo en que **LA-8** no recibió agua del arroyo Turbio ni del túnel está marcado por una fuerte baja en la concentración de sulfato (fuerte influencia del arroyo Canito, más diluido en sulfato). La influencia del cierre de las válvulas del tapón del túnel no se nota en esta serie temporal, como sí ocurre desde que la TD3 descargó aguas arriba de **LA-8** y la concentración de sulfato aumentó nuevamente a valores más comparables al periodo previo a las obras de desvío.

La serie temporal de carga de sulfato muestra una tendencia decreciente previo a los desvíos, una estabilización a valores en torno a ~300 kg/h durante el periodo en que **LA-8** no recibió agua de TD3 y una tendencia creciente con el aporte del agua del arroyo Turbio y túnel desde que TD3 aportó agua a este sistema, hasta valores generalmente entre 700 y 1300 kg/h.

Las estaciones SW-9 y LA-16 muestran series temporales de sulfato similares, con una mayor frecuencia de medición en LA-16, ya que es el punto de cumplimiento. Las concentraciones de sulfato fueron muy variables durante el periodo de túnel abierto, con periodos de concentración baja coincidentes con eventos de caudal alto. Luego del cierre de las válvulas del tapón del túnel, disminuyó la frecuencia de medición aunque las concentraciones continuaron con alta variabilidad relacionadas en general a variabilidad de caudales. No se observa claramente una tendencia creciente o decreciente luego del cierre del túnel.

En cuanto a la carga de sulfato, las series temporales de ambas estaciones muestran un aumento durante el periodo de túnel abierto, con una tendencia decreciente luego del cierre de las válvulas y levemente más marcada luego del cese de agregado de cal apagada. Desde aproximadamente enero de 2021, los valores de carga de sulfato son variables aunque en torno a los previos a la apertura del túnel.


::: {.content-hidden when-format=“docx”}
{{< include qmd/fig/_sulfatos.qmd >}}
:::

La figura anterior, presenta series temporales de carga metálica de sulfatos (en kg/hr) para diferentes estaciones de monitoreo, registradas desde el año 2010 a la fecha.^[Las series temporales fueron obtenidas a partir de una aplicación de base de datos de monitoreo implementada para el proyecto Lama. Otras visualizaciones basadas en eventos estacionales, mensuales o anuales, pueden obtenerse en el siguiente [enlace](https://averri.shinyapps.io/ARMA8U0/){target="_blank"}]


### Acidez de las aguas (pH)

Durante la etapa de túnel abierto, el pH registrado en la estación **TUN-1** fue muy variable de acuerdo con el ritmo de adición de cal apagada, aunque en general por encima de un valor de 5. En el caso del arroyo Turbio (**LA-1A**), el valor más frecuente estuvo entre 3 y 3,5, estabilizándose a un valor más cercano a 3 luego del cierre de las válvulas del tapón, posiblemente debido a un aumento del caudal y menor impacto de los deshielos en este parámetro. El pH en el portal del túnel (**MAR-1**) tiende a presentar valores comprendidos en el rango de pH del arroyo Turbio desde el cierre de las válvulas de la obturación.


El pH fue variable en LA-8, pero en valores relativamente altos (en torno a ~4) durante parte del periodo de túnel abierto y todo el periodo en que TD3 descargaba directamente en el río de Las Taguas (el agua de esta tubería no llegaba a **LA-8**). Se observa una disminución muy leve del pH luego del cierre del túnel y en especial de abril de 2019 (cese de agregado de cal en el portal del túnel) y una disminución marcada luego del restablecimiento de la descarga de TD3 aguas arriba de **LA-8**, hacia valores en torno a 3,4, más cercanos a los valores del arroyo Turbio.


El pH en **SW-9** y **LA-16** se presentó ampliamente variable a lo largo de todo el registro (mayormente ~4,5-8,5), con una mayor frecuencia de medición durante el periodo de túnel abierto. La tendencia de los valores de pH fue levemente decreciente luego del cierre de las válvulas y luego del cese de adición de cal apagada, aunque aún dentro del rango de valores registrados previamente a la excavación del túnel y aún durante el periodo de túnel abierto. Estos valores confirman estudios preliminares. ^[El modelo de mezclas(Goldsim) desarrollado en 2018, con el objetivo de predecir potenciales impactos en la calidad de agua en el río de Las Taguas a distintos caudales asumidos, predijo que no habrá impacto tangible en **SW-9** hasta caudales residuales en el túnel de al menos 15 L/s.].

::: {.content-hidden when-format=“docx”}
{{< include qmd/fig/_pH.qmd >}}
:::

La figura anterior, presenta la serie temporal del pH (en unidades de pH) desde el año 2010 a la fecha.^[Las series temporales fueron obtenidas a partir de una aplicación de base de datos de monitoreo implementada para el proyecto Lama. Otras visualizaciones basadas en eventos estacionales, mensuales o anuales, pueden obtenerse en el siguiente [enlace](https://averri.shinyapps.io/ARMA8U0/){target="_blank"}]


### Aluminio

La serie temporal de concentración de Aluminio en **LA-1A** muestra concentraciones muy variables (~100-450 mg/L) previamente a la apertura del túnel, con un rango similar aunque con menor frecuencia de medición durante el periodo de túnel abierto, posiblemente debido al congelamiento de su cauce reducido por efecto drenante del túnel. Luego del cierre de las válvulas, se observa una tendencia creciente fuerte, la cual permanece en aumento pero con pendiente más suave desde aproximadamente abril de 2019. Las tendencias de la concentración de aluminio en **MAR-1** y **TUN-1** muestran una mejor definición de dicha variabilidad (mayor frecuencia de medición). La tendencia en **MAR-1** es también creciente luego del cierre del túnel aunque con contenidos menores, sugiriendo que la mayor fuente de aluminio en el sector es el arroyo Turbio más que el macizo rocoso (lo mismo para el sulfato).

Las series temporales de la carga de aluminio muestran una tendencia estable luego del cierre del túnel tanto para LA-1A, a pesar de que su caudal se mostró con tendencia decreciente en este periodo, como para **MAR-1**, con caudales residuales bajos (hoy en el orden de 5 L/s).

De forma similar a la del sulfatos, las series temporales de concentración y carga de aluminio en **LA-8** decrecen, se estabilizan en valores bajos en el periodo en que **LA-8** registraba calidad de agua principalmente de la cuenca de Canito, y muestran una tendencia de aumento luego de que **LA-8** recibió la descarga de TD3. La influencia del cierre del túnel y del cese de adición de cal es de mucha menor relevancia para este parámetro.

Las series temporales muestran una evolución similar en las estaciones **SW-9** y **LA-16**, tanto en concentración como en carga de soluto. La concentración de aluminio es ampliamente variable y presenta una tendencia generalmente ascendente a lo largo del registro en ambas estaciones, con valores relativamente altos durante la etapa de túnel abierto. La tendencia se observa ascendente, desde valores bajos, luego del cierre de las válvulas, con concentraciones aún dentro del rango de la etapa de túnel abierto aunque con amplia variabilidad.

Los picos en carga de aluminio coinciden aproximadamente con picos en el caudal registrado en la boca del túnel cuando se encontraba abierto. La tendencia de la carga de aluminio se estabiliza luego del cierre de las válvulas, aunque con mediciones puntuales por encima de la tendencia general.


::: {.content-hidden when-format=“docx”}
{{< include qmd/fig/_aluminio.qmd >}}
:::

La figura anterior, presenta la serie temporal de carga metálica de aluminio (en kg/hr) desde el año 2010 a la fecha.^[Las series temporales fueron obtenidas a partir de una aplicación de base de datos de monitoreo implementada para el proyecto Lama. Otras visualizaciones basadas en eventos estacionales, mensuales o anuales, pueden obtenerse en el siguiente [enlace](https://averri.shinyapps.io/ARMA8U0/){target="_blank"}]

### Hierro

En el sector del túnel, la concentración de hierro fue variable en **LA-1A** (~200-500 mg/L), con mediciones más espaciadas aproximadamente entre febrero de 2014 y diciembre de 2017. A partir del cierre de las válvulas del tapón del túnel, se observa una tendencia creciente fuerte aproximadamente hasta septiembre de 2018 y luego una tendencia más suave aunque aún creciente. Las concentraciones de hierro registradas en **MAR-1** y **TUN-1** fueron variables aunque relativamente altas en la etapa de túnel abierto, disminuyeron con el cierre del túnel (~30-60 mg/L) y luego mostraron un aumento al principio empinado que evolucionó a una tendencia levemente ascendente en torno a concentraciones entre ~200 y 380 mg/L. Las cargas de hierro en los puntos de este sector muestran tendencias diferentes luego del cierre de las válvulas, con un rango amplio entre ~50 y 110 Kg/h en **LA-1A** y estabilizado en cargas muy bajas (~5 kg/h) en **MAR-1**.

En **LA-8**, la concentración de hierro se observa en un rango amplio (~20-100 mg/L), pero de tendencia estable previamente al periodo de descarga de TD3 directamente en el río Las Taguas, y desciende a valores muy bajos (en torno a 5mg/L) en el periodo dicho periodo. Luego del restablecimiento de la descarga de TD3 en LA-8 , los valores de concentración se recuperaron aunque la tendencia que se mantiene hasta la actualidad es ascendente. La serie temporal de carga de hierro muestra también una tendencia ascendente luego del restablecimiento de la descarga de TD3 en TD4.

Las concentraciones de hierro medidas en **SW-9** y **LA-16** durante el periodo de túnel abierto se presentan en un rango amplio, aunque con una mayor frecuencia de valores relativamente altos en comparación con la etapa previa al túnel. Luego del cierre de las válvulas, se observa una disminución general de las concentraciones de hierro y la tendencia parece ser estable, aunque el rango de valores medidos aún es amplio. La carga metálica de hierro muestra una tendencia en general estable y rango más estrecho de valores comparado a la concentración.


::: {.content-hidden when-format=“docx”}
{{< include qmd/fig/_hierro.qmd >}}
:::

La figura anterior, presenta la serie temporal de carga metálica de hierro (en kg/hr) desde el año 2010 a la fecha.^[Las series temporales fueron obtenidas a partir de una aplicación de base de datos de monitoreo implementada para el proyecto Lama. Otras visualizaciones basadas en eventos estacionales, mensuales o anuales, pueden obtenerse en el siguiente [enlace](https://averri.shinyapps.io/ARMA8U0/){target="_blank"}]



### Impactos en la calidad de agua del arroyo Turbio

Los informes de monitoreo desde la etapa de línea de base y los distintos estudios hidroquímicos han mostrado que las concentraciones más altas en sulfato, aluminio, hierro y cobre (además de otros metales como zinc, níquel y cobalto) provienen de la cuenca del arroyo Turbio, cuya cabecera escurre por la zona de intensa alteración hidrotermal del yacimiento Pascua-Lama. De esta forma, el arroyo Turbio es un contribuyente importante de los parámetros mencionados al río de Las Taguas.


En el sector del túnel, el pH ligeramente más alto registrado previo al tratamiento (**MAR-1**) en comparación con el arroyo Turbio, puede deberse a un consumo menor de acidez por parte del cemento del revestimiento del túnel y/o una mayor influencia de la infiltración de agua de deshielo en el macizo. La carga de sulfato disminuyó con la disminución del caudal en el arroyo Turbio durante el drenado de su subálveo por el túnel, luego se recuperó rápidamente luego del cierre de las válvulas, por recuperación de su caudal y posible redisolución de yeso precipitado durante caudal bajo, y luego mostró una tendencia decreciente. En el portal del túnel, la carga de sulfato se ha mantenido en torno a un valor muy bajo en el orden de 45 kg/h. Las cargas metálicas de aluminio, hierro y cobre presentaron una tendencia decreciente en el periodo de drenaje libre del túnel, con una recuperación y una estabilización luego del cierre de las válvulas. Estas cargas se mantienen en valores mínimos en el portal luego de la obturación del túnel.



### Impactos en la calidad de agua del río Las Taguas

En **LA-8**, estación actual de monitoreo inmediatamente aguas arriba de la confluencia con el río de Las Taguas, el pH aumentó durante el periodo en que el principal contribuyente fue el arroyo Canito, es decir, cuando el agua del arroyo Turbio y túnel se conducía a través de TD3 hasta el río de Las Taguas. El pH retornó a sus valores previos a las obras de desvío luego del restablecimiento de la descarta de TD3 aguas arriba de **LA-8** en la cuenca de Canito. Las cargas de sulfato, aluminio, hierro y cobre mostraron una evolución similar, con una disminución y estabilización en valores bajos durante el periodo de desvío de TD3 y una tendencia ascendente hacia valores previos a los desvíos luego del restablecimiento de la descarga de TD3 en el sector de **LA-8**.


En el sector del río de Las Taguas, si bien el pH se encuentra actualmente dentro del rango establecido antes de la apertura del túnel, ha decrecido desde el cierre del túnel y la mayor parte de los puntos se ha estabilizado en valores en torno a 5-6. Las cargas de sulfato, aluminio, hierro y cobre mostraron una evolución similar con valores relativamente altos durante el periodo de túnel abierto y una tendencia a estabilizarse en valores más bajos luego del cierre del túnel, cercanos a los previos a la excavación del túnel. 

Con los datos disponibles, pueden realizarse estimaciones expeditivas para obtener una primera idea de las contribuciones más importantes del sector del túnel y arroyo Turbio al río de Las Taguas. La fracción aproximada de sulfatos del arroyo Turbio puede estimarse en aproximadamente 20-25%, mientras que la fracción actual desde el portal sería del 2% o inferior. La contribución de aluminio desde el portal del túnel (**TUN-1**) fue de más del 50% durante el periodo de túnel abierto y adición de cal, disminuyendo al 3-5% luego del cierre. 

Actualmente, la principal contribución de aluminio al río de Las Taguas proviene del arroyo Turbio (~40-60%). Situaciones similares se observan para hierro y cobre desde el portal del túnel, con contribuciones generalmente superiores al 60% durante el periodo de túnel abierto y adición de cal, y fracciones actuales de ~4-5% desde los caudales residuales (**MAR-1**). El mayor contribuyente actual de hierro y cobre al río de Las Taguas es el arroyo Turbio (en general más del 70% de la carga metálica).


### Resumen


- La influencia de la obturación del túnel en los parámetros de calidad de aguas fue evaluada por medio de las cargas de soluto. Se evaluó además el pH como un parámetro indicador relacionado a la contribución de agua ácida y el tratamiento de regulación con cal apagada.

- En el sector del túnel, los cambios de pH más relevantes se dieron en el portal por la adición de cal, valores que están tendiendo a estabilizarse luego del cierre del túnel y cese del tratamiento de adición de cal. Las cargas de solutos están mostrando una tendencia a valores previos al drenado por el túnel en el arroyo Turbio y se mantienen en valores muy bajos y estables en el portal.

- Los cambios en la calidad del agua superficial en LA-8 están relacionados principalmente a las obras de desvío, principalmente la tubería TD3, la cual descargó el agua del arroyo Turbio y del túnel entre 2014 y fines de 2020, para luego descargar en la tubería TD4 y restablecer el agua monitoreada en **LA-8**.

- Actualmente, las cargas más significativas de sulfato y metales (Al, Fe y Cu, entre otros) provienen actualmente del arroyo Turbio, cuyo caudal ha aumentado luego del inicio de la operación de la obra de obturación del túnel y tiende a valores previos a la construcción del túnel. Las cargas de sulfato y metales provenientes del portal del túnel son ínfimas (fracciones de 2-5%) y estables, y no son distinguibles en el registro del río de Las Taguas.
