## Conclusiones


Las presiones hidrostáticas máximas registradas se ajustan a los valores predichos por los modelos hidrogeoeogicos desarrollados por SRK [-@srkconsulting2015, -@srkconsulting2016] y Piteau [-@piteauassociates2022]. No han presentado variaciones significativas desde el cierre de válvulas. Luego, el sistema de obturación funciona de acuerdo a lo previsto. 


La obturación del †únel ha estado expuesta a eventos sismicos moderados desde su contrucción y no se han regisstrado incrementos significativos en las presiones hidrostáticas de los piezómetros aguas-arriba (PA*). La obturación fue diseñada para sportar en servicio un sismo máximo de diseño con un período de retorno comprendido entre 1:2500 y 1:5000 años con un factor de seguridad a la falla cercano a 1.40. 

El sistema de monitoreo de presiones del tapón, compuesto por doce piezómetros, fue diseñado específicamente para registrar las variaciones de los niveles piezométricos durante la etapa de llenado del túnel, con el objetivo de controlar las presiones en este período transitorio. El plan de monitoreo previsto en el diseño se ejecutó con éxito durante los años de operación de la obturación. 


La estabilización de las series temporales de presiones en los rangos actuales, desde el cierre de válvulas hasta la fecha, es una validación los parámetros de diseño originales y los rangos estimados de presiones y caudales por los modelos hidrogeológicos implementados durante las etapas de diseño. Los datos demuestran que la estructura es segura y se comporta de acuerdo con lo previsto. 

Es importante destacar que, si bien hemos continuado realizando lecturas de presión en los años posteriores al llenado, la necesidad crítica de mantener este sistema de monitoreo ha disminuido considerablemente, dado que las presiones se han estabilizado según los valores previstos por el modelo hidrogeológico. En consecuencia, se abre la posibilidad de descontinuar el monitoreo de presiones en el futuro, sin comprometer la seguridad y eficiencia del tapón.

Los flujos de agua medidos aguas abajo del tapón, corresponden exclusivamente a la infiltración del macizo rocoso en sectores de fracturas ya previstas y mapeadas en los modelos hidrogeológicos. No se ha detectado flujo de agua proveniente de la interface entre la obturación y el macizo rocoso. Las variaciones relevantes y medibles en el caudal del río de Las Taguas, desde su punto de confluencia en **LA-8**, están relacionadas principalmente a años hidrológicos de distinta característica y no al desarrollo del túnel ni a su posterior obturación. La obturación del túnel Marcelo es un mecanismo eficiente para la contención del agua que drenaría a túnel abierto, manteniendo caudales residuales (\~5 L/s) de aproximadamente un 25% de los permitidos por la Autoridad (20 L/s). Estos caudales residuales se deben exclusivamente a zonas de infiltración preferencial del macizo rocoso aguas abajo de la obturación

En relación a la calidad de aguas, la influencia de la obturación del túnel en los parámetros de calidad de aguas fue evaluada por medio de las cargas de soluto. Se evaluó además el pH como un parámetro indicador relacionado a la contribución de agua ácida y el tratamiento de regulación con cal apagada. En el sector del túnel, los cambios de pH más relevantes se dieron en el portal por la adición de cal, valores que están tendiendo a estabilizarse luego del cierre del túnel y cese del tratamiento de adición de cal. Las cargas de solutos están mostrando una tendencia a valores previos al drenado por el túnel en el arroyo Turbio y se mantienen en valores muy bajos y estables en el portal. Los cambios en la calidad del agua superficial en **LA-8** están relacionados principalmente a las obras de desvío y manejo de aguas, principalmente a los cambios en la tubería TD3. En la actualidad, las cargas más significativas de sulfato y metales (Al, Fe y Cu, entre otros) provienen actualmente del arroyo Turbio, cuyo caudal ha aumentado luego del cierre del túnel y tiende a valores previos al túnel. Las cargas de sulfato y metales provenientes del portal del túnel son ínfimas (fracciones totales de 2-5%) y estables y no son distinguibles en el registro de monitoreo del río de Las Taguas.

Los resultados de las auditorías de estabilidad estructural del tapón han constatado la integridad estructural de la obturación de concreto y la ausencia de filtraciones en la interfaz indicando en cada una de ellas que el sistema de Obturación del Túnel Marcelo se encuentra operando dentro de los parámetros previstos en el modelo de análisis hidrogeológico, sísmico, geotécnico y estructural.


Informe elaborado por:

Camilo de Los Hoyos. *Consultor Principal (Geoquímica)*. 
Fermín Garate. *Consultor Principal (Ingenieria Estructural)*. 
Alejandro Verri Kozlowski. *Consultor Corporativo (Geotecnia Sísmica)*. 
**SRK Consulting (Argentina)**

