
:::  {.panel-tabset  .content-hidden when-format=“docx” .content-width-wide}

### PA01(U)

```{r include=knitr::is_html_output()}
piezo_code <- c("PA01(U)")
year_min <- 2010
year_max <- 2024
time_width <- 50

plot.type <- c("point","average")
Y1.max <- NULL
Y2.max <- NULL
source("qmd/fig/P_day.R")

PLOT
```
### PA02(U)

```{r include=knitr::is_html_output()}
piezo_code <- c("PA02(U)")
year_min <- 2010
year_max <- 2024
time_width <- 50

plot.type <- c("point","average")
Y1.max <- NULL
Y2.max <- NULL
source("qmd/fig/P_day.R")

PLOT
```

### PA03(U)

```{r include=knitr::is_html_output()}
piezo_code <- c("PA03(U)")
year_min <- 2010
year_max <- 2024
time_width <- 50

plot.type <- c("point","average")
Y1.max <- NULL
Y2.max <- NULL
source("qmd/fig/P_day.R")

PLOT
```
### PA04(D)

```{r include=knitr::is_html_output()}
piezo_code <- c("PA04(D)")
year_min <- 2010
year_max <- 2024
time_width <- 50

plot.type <- c("point","average")
Y1.max <- NULL
Y2.max <- NULL
source("qmd/fig/P_day.R")

PLOT
```

### PA05(D)

```{r include=knitr::is_html_output()}
piezo_code <- c("PA05(D)")
year_min <- 2010
year_max <- 2024
time_width <- 50

plot.type <- c("point","average")
Y1.max <- NULL
Y2.max <- NULL
source("qmd/fig/P_day.R")

PLOT
```

### PA06(D)

```{r include=knitr::is_html_output()}
piezo_code <- c("PA06(D)")
year_min <- 2010
year_max <- 2024
time_width <- 50

plot.type <- c("point","average")
Y1.max <- NULL
Y2.max <- NULL
source("qmd/fig/P_day.R")

PLOT
```
### PB01(D)

```{r include=knitr::is_html_output()}
piezo_code <- c("PB01(D)")
year_min <- 2010
year_max <- 2024
time_width <- 50

plot.type <- c("point","average")
Y1.max <- NULL
Y2.max <- NULL

source("qmd/fig/P_day.R")

PLOT
```

### PB02(D)

```{r include=knitr::is_html_output()}
piezo_code <- c("PB02(D)")
year_min <- 2010
year_max <- 2024
time_width <- 50

plot.type <- c("point","average")
Y1.max <- NULL
Y2.max <- NULL

source("qmd/fig/P_day.R")

PLOT
```

### PB03(D)

```{r include=knitr::is_html_output()}
piezo_code <- c("PB03(D)")
year_min <- 2010
year_max <- 2024
time_width <- 50

plot.type <- c("point","average")
Y1.max <- NULL
Y2.max <- NULL

source("qmd/fig/P_day.R")

PLOT
```

### PB04(D)

```{r include=knitr::is_html_output()}
piezo_code <- c("PB04(D)")
year_min <- 2010
year_max <- 2024
time_width <- 50

plot.type <- c("point","average")
Y1.max <- NULL
Y2.max <- NULL

source("qmd/fig/P_day.R")

PLOT
```

### PB05(D)

```{r include=knitr::is_html_output()}
piezo_code <- c("PB05(D)")
year_min <- 2010
year_max <- 2024
time_width <- 50

plot.type <- c("point","average")
Y1.max <- NULL
Y2.max <- NULL

source("qmd/fig/P_day.R")

PLOT
```

### PB06(D)

```{r include=knitr::is_html_output()}
piezo_code <- c("PB06(D)")
year_min <- 2010
year_max <- 2024
time_width <- 50

plot.type <- c("point","average")
Y1.max <- NULL
Y2.max <- NULL

source("qmd/fig/P_day.R")

PLOT
```


### All

```{r include=knitr::is_html_output()}
piezo_code <- c("PA01(U)","PA02(U)","PA03(U)","PA04(D)","PA05(D)","PA06(D)","PB01(D)","PB02(D)","PB03(D)","PB04(D)","PB05(D)","PB06(D)")
year_min <- 2010
year_max <- 2024
time_width <- 50

plot.type <- "average"
Y2.max <- 240
Y2.label <- "Presión última de servicio [mca]."
Y1.label <- "Presión máxima de diseño [mca]."
Y1.max <- 140

source("qmd/fig/P_day.R")

PLOT
```


:::





